name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    concurrency:
      group: terraform-apply-${{ github.ref }}
      cancel-in-progress: true
    defaults:
      run:
        working-directory: ./infra
    steps:
      - uses: actions/checkout@v4
      
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - run: terraform init -input=false
      - run: terraform apply -input=false -auto-approve
