name: Terraform Destroy

on:
  workflow_dispatch: # Manual trigger only, no inputs for full automation

env:
  AWS_REGION: us-east-1
  TF_WORKING_DIR: ./infra
  ENVIRONMENT: dev  # Hardcoded to dev environment for full automation

jobs:
  terraform-destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0
      
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init
      
      - name: Terraform Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          echo "⚠️ DESTROYING INFRASTRUCTURE FOR DEV ENVIRONMENT ⚠️"
          terraform destroy -auto-approve -var="environment=dev"
